name: BUILD

on:

  pull_request:
    branches: [ master ]

jobs:

  BUILD:

    runs-on: [ self-hosted, docker, linux ]

    steps:


      - name: Clone tests repo
        uses: actions/checkout@v2
        with:
         repository: company/ci-tests
         clean: 'true'
         ref: master


      - name: Build servers bins
        run: build_bins.sh

