name: RUN
 
on:

  workflow_run:
    workflows: ["BUILD"]
    types: [completed]

jobs:

  RUN:

    runs-on: [ self-hosted, docker, linux, server-tests ]
    
      - name: Run Tests
        run: run_tests.sh
